// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/
	//[puppy] RefineUI Options
	int refine_announce_success;
	int refine_announce_broken;
	int refine_option_announce;
	int refine_option_color;
	int refine_option_color_self;
	int refine_broken_color;
	int refine_normal_color;
	int blacksmith_downgrade;

	int32 trickdead_noexp;

	/*
 	////Max Trap [Hyroshima]
	//int skill_max_trap;
	//int global_max_trap;

	int32 asura_absorb_cast_cancel;
	int32 asura_dispell_cast_cancel;
	int32 block_body_relocation_ankle;
	int32 block_body_relocation_spiderweb;
	//int32 block_body_relocation_confine;
	int32 block_back_slide_ankle;
	int32 block_back_slide_spiderweb;
	int32 block_high_jump_ankle;
	int32 block_high_jump_spiderweb;
	int32 endure_hit;
	int32 gank_percent;

	int32 blitz_damage_divide;
	int32 sonic_blow_autoattack;
	int32 bowling_bash_multi_hit;
	int32 bowling_bash_min_count_re;
	int32 bowling_bash_max_count_re;
	int32 holy_cross_2spear_weapon;
	int32 sonic_acceleration_dmg;
	int32 backstab_dagger_hit;
	int32 pvp_mvp_map;
	//int32 broadcast_sound;
	//int32 sc_buff_effect_boss;
	int32 berserk_provork_lv;
	int32 bowlingbash_reduce_dmg_not_2hsw;
	//int32 sub_ele_capping;
	int32 sanctuary_disable;
	//int32 shadow_weapon_view;
	//int32 shadow_weapon_allow_empty_hand;
	//int32 shadow_weapon_fallback;
	//int32 blacksmith_downgrade;
	*/
