// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),

BUILDIN_DEF(recal_status,""),
BUILDIN_DEF(magnus_all, "i"),
BUILDIN_DEF(grandcross_nodmg_myself, "i"), // puppy grandcross_nodmg_myself

BUILDIN_DEF(getmapmoblist, ""), //puppy

BUILDIN_DEF(skillstrinfo,"v"),
BUILDIN_DEF(skillintinfo,"ii"),
BUILDIN_DEF(autoattackstrinfo,"i?"),
BUILDIN_DEF(autoattackintinfo,"i?"),
BUILDIN_DEF(autoattackset,"s"),
BUILDIN_DEF(autoattackclear,"i"),
BUILDIN_DEF(clear2,""),
BUILDIN_DEF(sc_check,"i"),
BUILDIN_DEF(autostart,"i?"),
BUILDIN_DEF(skillinfocheck,"ii"),
